version: '3.5'

services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db
    depends_on: 
      - db
  redis:
    image: "redis:alpine"
    volumes:
      - "./redis_data:/data"
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: example
    volumes:
      - "./database:/var/lib/postgresql/data"

volumes:
  db:
  redis: